# CMEMS product information for COPERNICUS downloader

datasets:
  - TARGET: OSISAF_ICEC
    PRODUCT_ID: SEAICE_GLO_SEAICE_L4_REP_OBSERVATIONS_011_009
    DATASET_ID: OSISAF-GLO-SEAICE_CONC_TIMESERIES-NH-LA-OBS
    PROCESSOR: EUMETSAT OSI SAF
    PROCESS_LEVEL: 4
    MODE: REP
    PERIOD: 19781025-20201231
    NCVAR: ice_conc
    NCSTD: total_standard_uncertainty
    NCFLG: status_flag
    FLGS: 0  # normal retrieval
    TPVAR: ICEC

  - TARGET: OSISAF_ICEC_CONT
    PRODUCT_ID: SEAICE_GLO_SEAICE_L4_REP_OBSERVATIONS_011_009
    DATASET_ID: OSISAF-GLO-SEAICE_CONC_CONT_TIMESERIES-NH-LA-OBS
    PROCESSOR: EUMETSAT OSI SAF
    PROCESS_LEVEL: 4
    MODE: REP
    PERIOD: 20211001-20220531
    NCVAR: ice_conc
    NCSTD: total_standard_uncertainty
    NCFLG: status_flag
    FLGS: 0  # normal retrieval
    TPVAR: ICEC

  - TARGET: ESACCI_SST
    PRODUCT_ID: SST_GLO_SST_L4_REP_OBSERVATIONS_010_024
    DATASET_ID: ESACCI-GLO-SST-L4-REP-OBS-SST
    PROCESSOR: ESA-CCI SST
    PROCESS_LEVEL: 4
    MODE: REP
    PERIOD: 19810901-20161231
    NCVAR: analysed_sst
    NCSTD: analysed_sst_uncertainty
    NCFLG: mask
    FLGS: 1 # water
    TPVAR: SST

  - TARGET: ESACCI_SST_CONC
    PRODUCT_ID: SST_GLO_SST_L4_REP_OBSERVATIONS_010_024
    DATASET_ID: C3S-GLO-SST-L4-REP-OBS-SST
    PROCESSOR: ESA-CCI SST
    PROCESS_LEVEL: 4
    MODE: REP
    PERIOD: 20170101-20221031
    NCVAR: analysed_sst
    NCSTD: analysed_sst_uncertainty
    NCFLG: mask
    FLGS: 1 # water
    TPVAR: SST

  - TARGET: OSTIA_SST
    PRODUCT_ID: SST_GLO_SST_L4_REP_OBSERVATIONS_010_011
    DATASET_ID: METOFFICE-GLO-SST-L4-REP-OBS-SST
    PROCESSOR: OSTIA SST
    PROCESS_LEVEL: 4
    MODE: REP
    PERIOD: 19811001-20220531
    NCVAR: analysed_sst
    NCSTD: analysis_error
    NCFLG: mask
    FLGS: 1 # water
    TPVAR: SST

  - TARGET: ESACCI_SCHL
    PRODUCT_ID: OCEANCOLOUR_GLO_BGC_L3_MY_009_107
    DATASET_ID: c3s_obs-oc_glo_bgc-plankton_my_l3-multi-4km_P1D
    PROCESSOR: ESA-CCI OC
    PROCESS_LEVEL: 3
    MODE: MY
    PERIOD: 19970904-20240430
    NCVAR: CHL
    NCSTD: NA
    NCFLG: NA
    FLGS: NA
    AGGREGATE: true
    TPVAR: SCHL

  - TARGET: CMEMSGLB_SCHL
    PRODUCT_ID: OCEANCOLOUR_GLO_BGC_L3_MY_009_103
    DATASET_ID: cmems_obs-oc_glo_bgc-plankton_my_l3-multi-4km_P1D
    PROCESSOR: Copernicus-GlobColour
    PROCESS_LEVEL: 3
    MODE: MY
    PERIOD: 19970904-20240529
    NCVAR: CHL
    NCSTD: CHL_uncertainty
    NCFLG: flags
    FLGS: 0 # water
    AGGREGATE: true
    TPVAR: SCHL

