#!/bin/bash

# File: assimilate.sh
# Author : Pavel Sakov # Date: 11 January 2010
# Corrected by Jiping Xie # Date: 5 June 2019
#
# Description:
#   This is a top level script for data assimilation in TOPAZ4.
#   It uses the prior art from TOPAZ3 and tries to simplify that existing
#   workflow based on possibilities open by the latest EnKF code.
#
#   This procedure is supposed to be called from main.sh. Otherwise your
#   assimilation_specs.sh may be outdated. If ran as a standalone script, it
#   should be launched from the directory one level up from here.
#
# WARNING:
#   Do not edit this file. Specify your custom settings in
#   "assimilation_specs.in" instead.

set -e # exit on error
set -u # exit on unset variables
set -p # nothing is inherited from the shell
set -x

MONITORINTERVAL=10 # time interval for periodic checks on job status
MONITORINTERVAL2=30 # time interval for periodic checks on job status
LAUNCHINTERVAL=5 # time interval for launching parallel jobs
nre=0 # number of members reassembled

#
# 1. Read and report specifications for the assimilation
#
echo "1. Reading specifications and checking configuration:"
source assimilation_specs.sh
export ANALYSISDIR BINDIR RESULTSDIR JULDAY ENSSIZE NPROC FORECASTDIR BACKUPBUFDIR MODELDIR HYCOMPREFIX PREPOBSDIR OUTPUTDIR NESTINGDIR OBSDIR ROOTDIR

echo "   JULDAY = ${JULDAY}"

# clean up
#
rm -rf ${ANALYSISDIR} ${PREPOBSDIR}
mkdir ${ANALYSISDIR}

echo "   Data types:"
for datatype in $OBSTYPES
do
    echo "     $datatype"
done

echo "   Directories:"
./SCRIPTS/check_directories.sh

echo "   EnKF parameters:"
cat enkf.prm | awk '{print "     "$0}'

./SCRIPTS/check_files.sh

